### PR TITLE
Fix CI and tests

### PR DESCRIPTION
**Pull request by jirkadanek**
This comments out a failing test and updates clang on Travis so that both CI builds (gcc and clang) succeed.

### CODE REVIEW

**Comment by jirkadanek** [comment]
The test "Capture-from-within 4pt-eye (square) nakade" succeeds with PR #12 applied. That means it is not necessary to comment it out. I will update this PR with that.

**Comment by pasky** [comment]
I think long-term, we should have a way to declare "known-to-fail" tests, but meanwhile as we have a github issue to remind us of this too and it's a really minor think, I think it's fine to comment it out in this specific case. Thanks!

**Comment by pasky** [comment]
So while the Travis indicator was green in the pull request, after merging it I got an email that says "still failing"...

**Comment by jirkadanek** [comment]
> I got an email that says "still failing"...

Because PR #12 added two more failing tests.

> I will update this PR with that.

I hoped you'd wait for me to do this. Never mind, I'll start a new PR.

**Pull request merged**
