### PR TITLE
Segfault on DCNN is back!

### PR DESCRIPTION
**Pull request by apetresc**
**NOTE**: This PR is _not_ meant to be merged, just to share some debugging code!

I keep on hitting the same segfault that @xlvector encountered in #32. The symptoms are identical: in `dcnn_get_moves()` (notably, a C++ file) you have `b->b` appear to be `NULL`, even though in the calling function (notably, a C file) has `b->b` non-`NULL`.

Apparently @xlvector solved his issue just by compiling without `MAC=1`, but unfortunately I believe that's a red herring as I can reproduce this issue in OS X _and_ Ubuntu 16.04 _and_ Ubuntu 14.04, with both GCC 5.4 and 4.8. It is very consistent for me.

I think I've tracked down the issue to a difference in struct-packing between C and C++. If I build the branch in this pull request, which simply prints out the offsets of the fourth and fifth members of the `board` struct,  I get the following:

```
uct_prior: board is at 0x0x7f608c06b9e0
uct_prior: address of board.captures is 0x0x7f608c06b9ec
uct_prior: address of board.komi is 0x0x7f608c06ba00
uct_prior: S_MAX is 4
dcnn_get_moves: board is at 0x7f608c06b9e0
dcnn_get_moves: address of board.captures is 0x7f608c06b9ec
dcnn_get_moves: address of board.komi is 0x7f608c06b9fc
dcnn_get_moves: S_MAX is 4
```

Notice how `board.captures` is perfectly aligned on both, but `board.komi` is 4 bytes later in `uct/prior.c`, but only 1 byte later in `dcnn.cpp`. So for some reason, C++ is allocating only one byte for `int captures[S_MAX]` (even though it knows S_MAX is 4). So then when `dcnn.cpp` looks at `b->b`, it's actually looking 4 bytes too early, into one of the `last_move` structs, and erroneously reads back a null pointer. Again, I can reproduce this on three different operating systems with three different GCC versions.

I'm not much of a C/C++ expert, but this seems like a bug, and the fact that it doesn't happen on your own machines makes it seem platform-dependent somehow. Anyone have any clues?

### CODE REVIEW

**Comment by apetresc** [comment]
(Hoping @lemonsqueeze or @pasky can take a look! :smile:)

**Comment by apetresc** [comment]
Okay, a slight breakthrough (I think!): it appears to be specifically related to the way C/C++ is aligning the struct, because by simply increasing the size of `captures` to `S_MAX + 1`, everything snaps into place; the offset of `komi` jumps from +12 to +32, even though we've only added one byte. So somehow we forced it to cross some alignment boundary and then the C and C++ code agrees. And once I do that, the DCNN code runs flawlessly!

So hopefully that helps diagnosis. Is there some good way to get diagnostics about how/why C++ is packing the `board` struct?

**Comment by pasky** [comment]
That's super strange - struct board is a pod structure and really ought to be aligned exactly the same in C and C++. Can you please make sure that you are using the same compiler version for C and C++ and something crazy (like clang for C, gcc for C++) isn't happenning? It'd be great if you could run ``make clean all V=1`` and paste the command lines corresponding to dcnn.cpp and board.c, and verify what are the final binaries called (possibly through symlinks) from the command lines.

I think everything would be quite happier if we minimized the C++ surface further, though - basically splitting out dcnn_get_moves() bottom half (after we construct data) to a separate C++ file and having everything else in a C file. Then we wouldn't need to have C++ compatible header files etc.

**Comment by lemonsqueeze** [comment]
> I think everything would be quite happier if we minimized the C++ surface further, though - basically splitting out dcnn_get_moves() bottom half (after we construct data) to a separate C++ file and having everything else in a C file. Then we wouldn't need to have C++ compatible header files etc.

I like the idea too,
Something like this ? (PR #59)
Will probably make it easier to compile on other platforms also

**Comment by lemonsqueeze** [comment]
Closing old issue, please reopen if still happening.

**Pull request closed without merging**
