### PR TITLE
Spring cleanup: the end

### PR DESCRIPTION
**Pull request by lemonsqueeze**
And the last one:
- Makefile cleanup: trimmed output, factored clean rules, figure out LOCALLIBS from SUBDIRS
- misc stuff: file perms, .gitignore, warnings ...
- ownermap and uct get_dead_groups() cleanup (fairly small changes)

t-unit:
- factored common code, cleaned up parser
- add gtp support, useful in some situations (and makes gtp parser even more open to abuse)
- set last move with `')'` in board diagrams instead of passing args to `moggy moves` and `moggy status`

Whew !

### CODE REVIEW

**Comment by pasky** [comment]
Oh, but astronomical spring ended yesterday already! :)

Thanks a lot for all these pull request. Unfortunately, to be completely honest, I'm currently so busy with Rossum.ai affairs that I'll be quite unlikely to find time to review and merge them in the coming months.

So, one thing I'm thinking about is - would you like to take over as Pachi's maintainer? I'd welcome that a lot!  We can figure out how to best do this - whether to create a pachi github.com organization or I can just give you full perms to the pasky/pachi repo.

**Comment by lemonsqueeze** [comment]
Indeed, i couldn't push the spring deadline much further =)

Oh wow, didn't know about Rossum.ai. I have a feeling we're only at the beginning of some very impressive applications of deep learning.

Thanks for your offer, i feel really honored. I'll be happy to take care of Pachi for a while, although there's still much i don't know about. I think it would be good if you can give advice from time to time, probably nobody knows Pachi as well as you do.

**Comment by lemonsqueeze** [comment]
Looks like spring cleanup turned into fall cleanup, and got bigger in the meantime =)
But here it is, i'm happy with the results.

I enabled dcnn build by default (and updated travis so we know if it breaks)
Also tried moving all the misc engines to a common `engines` directory. I think i like it this way: builds  faster, and feels more tidy. dcnn engine is where it belongs at last (split from dcnn.c)

I've tried to keep to cleanup changes only here, so behavior is unchanged before and after the cleanup PRs. Still there are some features / fixes that made it in (too much trouble to take them out) :
- board diagrams show score estimate based on ownermap
- dcnn engine checks invalid moves
- reworked gogui analyze commands (simpler / saner)

Other changes should be fairly clear from the logs. The gogui cleanup is a big one: managed to untangle most of it from uct and avoid static buffer hacks for livegfx. It's pretty much engine generic now.

If you have time let me know what you think.
Otherwise should be fine, kgs bot based on this has been playing for a while without issues.

**Comment by pasky** [comment]
Very cool! :) Does the KGS bot have a rank? What nick is it?

**Comment by pasky** [comment]
(I'm afraid I won't be able to review the changes, though. :-( )

**Comment by lemonsqueeze** [comment]
> Very cool! :) Does the KGS bot have a rank? What nick is it?

Yes, pachipachi is 2d on kgs, playing 5k sims on raspberry pi =)
(well, -t =5000:15000 actually)

**Comment by pasky** [comment]
That's amazing! I think I was wondering a few times who is running pachipachi. :)

Hmm. I have a bunch of spare Raspberry PIs ;)

**Comment by lemonsqueeze** [comment]
Yes it's amazing, it seems about as strong now playing at 15k as before when it was playing 180k !
Still wondering how this happened. Kgs ranks must have drifted or something. Or maybe it's just that playing faster, people think less !

**Pull request merged**
