### PR TITLE
autotest-show-diagram

### PR DESCRIPTION
**Pull request by lemonsqueeze**
Here it is !

### CODE REVIEW

**Comment by jmoudrik** [comment]
Hmm, why did you find it necessary to change the sh to bash? With sh it
should work with any posix-compliant shell, instead of only bash; a few
commits back, I actually tried to make the utils as posix compliant as
possible.

What do you actually use for /bin/sh?

Regards,
Josef

**Comment by lemonsqueeze** [comment]
Hi Josef,
Sorry about that, I thought it wasn't intentional.
I changed it as it didn't work for me with Ubuntu 14, I think they have dash acting as /bin/sh now ...
Should I take it out and make it a separate issue ?

**Comment by pasky** [comment]
Josef, do you use some system that actually lacks /bin/bash ?
I'd expect it's pretty much universal among Pachi developer audience,
so this might be a cheap way to fix any hiccups...

**Comment by jmoudrik** [comment]
No, I do not. I am asking because the original scripts had /bin/sh and I
tried to make them posix compliant to work with e.g. dash. So I am
surprised it actually does not work. Generally I think it is better not to
use bash unless necessary.

In case of pachi, however, I think focus should be on more important
matters, so bash is ok afaik.

Josef

**Comment by pasky** [comment]
Thanks! We may want to show both confidences like %%% #### for example to make it easier for low-game-count scenarios (which aren't suitable for tuning, but are fine for sanity checks), but at any rate, I have merged the current version already.

**Pull request merged**
